            <div class="container page-container">
              <div class="row">
                <div class="jumbotron">
                  <h3><img src="img/license.png" />License</h3>
	              <p>The <a href="https://github.com/masterchain/masterchain-world/">code</a> is distributed under <a href="LICENSE.txt" target="_blank">Masterchain</a> license.</p>
                  <p>This site uses <a href="http://glyphicons.com" target="_blank">glyphicons</a> fonts.</p>
                </div>
              </div>
            </div>
