            <div class="container page-container">
                <div class="row">
                    <div class="jumbotron">
                        <h3><img src="img/about.png" /> About</h3>
	                    <p>This is the web UI of <a href="https://github.com/grazcoin/mastercoin-tools" target="_blank">mastercoin-tools</a> (<a href="License.html">License</a>).</p>
                            <p>Links to <a href="/professional.html">additional tools</a>.</p>
                            <p></p>
                            <p>Developers: <a href="https://bitcointalk.org/index.php?action=profile;u=61204">Grazcoin</a> and <a href="https://bitcointalk.org/index.php?action=profile;u=153554">Grimentz</a>.</p>
                    </div>
                </div>
            </div>
