<!doctype html>

<!--
    Copyright Masterchain Grazcoin Grimentz 2013-2014
    https://github.com/masterchain/masterchain-world
    https://masterchain.info
    masterchain@@bitmessage.ch
    https://masterchain.info/LICENSE.txt
-->

<html ng-app="myApp">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
      <meta name="google" value="notranslate" />
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="shortcut icon" href="ico/favicon.png">
      <title>
